import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import { Navbar, NavbarBrand, NavbarContent, NavbarItem } from "@nextui-org/navbar"
import { Link } from "@nextui-org/link"

import { UiProviders } from "../helpers/providers/UiProviders";
import QrProvider from '../helpers/providers/QrProvider'

const inter = Inter({ subsets: ['vietnamese'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='light'>
      <body className={`prose-lg ${inter.className}`}>
        <UiProviders>
          <Navbar isBordered className='bg-background-200'>
            <NavbarBrand>
              <p className='font-bold'>BRAND NAME</p>
            </NavbarBrand>
            <NavbarContent className="sm:flex gap-4" justify="center">
              <NavbarItem>
                <Link color="foreground" href="#">
                  Features 1
                </Link>
              </NavbarItem>
              <NavbarItem>
                <Link color="foreground" href="#">
                  Features 2
                </Link>
              </NavbarItem>
            </NavbarContent>
            <NavbarContent className="sm:flex gap-4" justify="end">
              <NavbarItem>
                <Link color="foreground" href="#">
                  Features 3
                </Link>  
              </NavbarItem>        
            </NavbarContent>            
          </Navbar>
          <div className="container mx-auto px-5 md:px-10">    
            <QrProvider>
              {children}              
            </QrProvider>        
          </div>          
        </UiProviders>
      </body>
    </html>
  )
}
